#此文件中不允许使用tab
source:      . #源文件的根目录 jekyll读取
destination: ./_site #jekyll生成静态文件的目录
plugins:     ./_plugins #
layouts:     ./_layouts #布局
include:     ['.htaccess'] #包含的文件或者目录
exclude:     [] #排除在外的目录或者文件 即不需要进行转换的目录和文件
keep_files:  ['.git','.svn']
timezone:    nil #时区
paginate: 5

safe:        false
#host:        0.0.0.0
baseurl:     /  #配置指定的url在服务器上运行站点
lsi:         false #发布相关的文章
